###Import the libraries

In [74]:
import math

import pandas as pd
import numpy as np

###Question 1
What's the version of Pandas that you installed?

You can get the version information using the __version__ field:



In [75]:
pd.__version__

'1.5.3'

###Download California Housing Prices dataset

In [19]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv

--2023-09-13 13:09:53--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1423529 (1.4M) [text/plain]
Saving to: ‘housing.csv.2’

housing.csv.2       100%[===================>]   1.36M  --.-KB/s    in 0.01s   

2023-09-13 13:09:53 (134 MB/s) - ‘housing.csv.2’ saved [1423529/1423529]



###Question 2
How many columns are in the dataset?

In [76]:
df = pd.read_csv('/content/housing.csv')
df.shape[1]

10

###Question 3
Which columns in the dataset have missing values?

In [77]:
df.columns[df.isnull().any()]

Index(['total_bedrooms'], dtype='object')

###Question 4
How many unique values does the `ocean_proximity` column have?

In [78]:
df['ocean_proximity'].nunique()

5

###Question 5
What's the average value of the `median_house_value` for the houses located near the bay?

In [79]:
houses_near_bay = df[df['ocean_proximity'] == 'NEAR BAY']
average_value = houses_near_bay['median_house_value'].mean()

print(f"{average_value:.3f}")

259212.312


###Question 6
1. Calculate the average of `total_bedrooms` column in the dataset.

In [80]:
mean_bedrooms = df['total_bedrooms'].mean()

print(f"{mean_bedrooms:.3f}")

537.871


2. Use the `fillna` method to fill the missing values in `total_bedrooms` with the mean value from the previous step.

In [81]:
df['total_bedrooms'] = df['total_bedrooms'].fillna(mean_bedrooms)

3. Now, calculate the average of `total_bedrooms` again.

In [82]:
new_mean_bedrooms = df['total_bedrooms'].mean()
print(f"{new_mean_bedrooms:.3f}")

537.871


4. Has it changed?

In [83]:
print("No" if math.isclose(new_mean_bedrooms, mean_bedrooms) else "Yes")

No


### Question 7

1. Select all the options located on islands.

In [88]:
islands_df = df[df['ocean_proximity'].isin(['ISLAND'])]
islands_df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8314    -118.32     33.35                27.0       1675.0           521.0   
8315    -118.33     33.34                52.0       2359.0           591.0   
8316    -118.32     33.33                52.0       2127.0           512.0   
8317    -118.32     33.34                52.0        996.0           264.0   
8318    -118.48     33.43                29.0        716.0           214.0   

      population  households  median_income  median_house_value  \
8314       744.0       331.0         2.1579            450000.0   
8315      1100.0       431.0         2.8333            414700.0   
8316       733.0       288.0         3.3906            300000.0   
8317       341.0       160.0         2.7361            450000.0   
8318       422.0       173.0         2.6042            287500.0   

     ocean_proximity  
8314          ISLAND  
8315          ISLAND  
8316          ISLAND  
8317          ISLAND  
8318          ISLAND

2. Select only columns `housing_median_age`, `total_rooms`, `total_bedrooms`.

In [89]:
islands_df = islands_df[['housing_median_age', 'total_rooms', 'total_bedrooms']]
islands_df

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

3. Get the underlying NumPy array. Let's call it `X`.

In [102]:
X = islands_df.to_numpy()
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

4. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.

In [100]:
XTX = X.T @ X
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

5. Compute the inverse of `XTX`.

In [101]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

6. Create an array `y` with values `[950, 1300, 800, 1000, 1300]`.

In [103]:
y = np.array([950, 1300, 800, 1000, 1300])
y

array([ 950, 1300,  800, 1000, 1300])

7. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.

In [104]:
w = XTX_inv @ X.T @ y

8. What's the value of the last element of `w`?

> **Note**: You just implemented linear regression. We'll talk about it in the next lesson.

In [105]:
w[-1]

5.699229455065586

### Submit the results

* Submit your results here: https://forms.gle/jneGM91mzDZ23i8HA
* You can submit your solution multiple times. In this case, only the last submission will be used
* If your answer doesn't match options exactly, select the closest one

* __Deadline__

 - The deadline for submitting is 18 September 2022 (Monday), 23:00 CEST (Berlin time).

 - After that, the form will be closed.